### ISSUE TITLE
this.state should be considered as IMMUTABLE

### ISSUE THREAD

**Issue by andrejkn** [rangle/react-workshop#5]
I see `this.state` being augmented all over the **TODO app**
e.g.
```javascript
cancelClick() {
    this.state.selectedIndex = -1;
    this.state.todo = {};
    this.setState(this.state);
}
```
This needs to be fixed:
```javascript
cancelClick() {
    this.setState({
        todo: {},
        selectedIndex: -1
    });
}
```
Also, you can use [shallow merge](https://facebook.github.io/react/docs/update.html#shallow-merge)
OR
Pass a function instead of an object to `this.setState()`

**Comment by andrewdamelio** [comment]
:+1:  :+1:  :+1:  - i'm going to make some changes to the Todo app after I finish the workshop - so watch out for that PR - i'd love your feedback!
